apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg
  namespace: demo
spec:
  version: "4.4.6"
  replicaSet:
    name: "mongo"
  replicas: 3
  init:
    script:
      scriptPath: "current"
      git:
        args:
          - --repo=https://github.com/Arnobkumarsaha/sync-test
          - --depth=1
          - --period=60s
          - --link=current
          - --root=/git
          # terminate after successful sync
          - --one-time
        # run as git sync user
        securityContext:
          runAsUser: 65533
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: WipeOut